### ISSUE TITLE
script not working

### ISSUE THREAD

**Issue by Sara-Samer** [abdelrahmanfekri/Udemy-With-React-Full-Website#2]
https://github.com/abdelrahmanfekri/Udemy-With-React-Full-Website/blob/331804a389ed1ac3a048fa2c51fa0f172d15342b/package.json#L20-L25

I couldn't run it on my machine since `set PORT=3006` works on windows only. I changed and ran it anyways just keep on mind trying to generalize your scripts

**Comment by abdelrahmanfekri** [comment]
I changed to work on port = 3000 but I changed json-server to work on 3003
