### ISSUE TITLE
this is DOM manipulation, which is not preferable in react. use `useState`  or `useRef` or any npm library 

### ISSUE THREAD

**Issue by Sara-Samer** [abdelrahmanfekri/Udemy-With-React-Full-Website#7]
https://github.com/abdelrahmanfekri/Udemy-With-React-Full-Website/blob/331804a389ed1ac3a048fa2c51fa0f172d15342b/src/components/Section.js#L41-L55

**Comment by abdelrahmanfekri** [comment]
Done, I changed all Dom manipulation with useRef it is easier thanks
